In [1]:
import pandas as pd
import numpy as np
import matplotlib as mtp

In [2]:
df_gdp = pd.read_csv('arquivos_base/gdp.csv', decimal='.', thousands=',')

In [3]:
df_gdp

,Country,Region,Year,GDP_pp
0,Afghanistan,"Middle East, North Africa, and Greater Arabia",1/1/1901,613.99
1,Afghanistan,"Middle East, North Africa, and Greater Arabia",1/1/1906,624.04
2,Afghanistan,"Middle East, North Africa, and Greater Arabia",1/1/1911,634.25
3,Afghanistan,"Middle East, North Africa, and Greater Arabia",1/1/1916,647.28
4,Afghanistan,"Middle East, North Africa, and Greater Arabia",1/1/1921,662.40
...,...,...,...,...
4414,Zimbabwe,Sub-Saharan Africa,1/1/1991,782.09
4415,Zimbabwe,Sub-Saharan Africa,1/1/1996,781.50
4416,Zimbabwe,Sub-Saharan Africa,1/1/2001,719.96
4417,Zimbabwe,Sub-Saharan Africa,1/1/2006,520.17
4418,Zimbabwe,Sub-Saharan Africa,1/1/2011,526.33

In [4]:
df_gdp.info()

<class 'pandas.DataFrame'>
RangeIndex: 4419 entries, 0 to 4418
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   4419 non-null   str
 1   Region    4419 non-null   str
 2   Year      4419 non-null   str
 3    GDP_pp   4419 non-null   float64
dtypes: float64(1), str(3)
memory usage: 138.2 KB

In [5]:
df_gdp.columns = 'Country', 'Region', 'Year', 'GDP_pp'
# erro ao chamar coluna 'GDP_pp'. Resolvido declarando colunas

In [6]:
df_gdp['GDP_pp'] = df_gdp['GDP_pp'].apply(lambda x: float(x))
# transformando coluna GDP_pp em float

In [7]:
df_gdp['Year'] = df_gdp['Year'].apply(lambda x: int(x.split('/')[2]))
# transformando coluna Year para datetime

In [8]:
df_gdp['Year'].value_counts()

Year
1991    193
1996    193
2001    193
1901    192
1906    192
1911    192
1916    192
1921    192
1926    192
1931    192
1936    192
1941    192
1946    192
1951    192
1956    192
1961    192
1966    192
1971    192
1976    192
1981    192
1986    192
2006    192
2011    192
Name: count, dtype: int64

In [9]:
df_gdp.groupby('Country').agg({'Year':'min'}).reset_index().sort_values(by='Year')
# um dos paises inicia a amostragem em 1991, diferente dos outros. Pais -> 'Kosovo'

         Country  Year
0    Afghanistan  1901
1        Albania  1901
2        Algeria  1901
3        Andorra  1901
4         Angola  1901
..           ...   ...
188    Venezuela  1901
189      Vietnam  1901
190  Yemen, Rep.  1901
191       Zambia  1901
88        Kosovo  1991

[193 rows x 2 columns]

In [12]:
df_ano_minimo = df_gdp.groupby('Country').agg({'Year':'min'}).reset_index().sort_values(by='Year')

In [15]:
df_ano_minimo['GDP_pp'] = df_gdp['GDP_pp']

In [16]:
df_ano_minimo

         Country  Year    GDP_pp
0    Afghanistan  1901    613.99
1        Albania  1901    624.04
2        Algeria  1901    634.25
3        Andorra  1901    647.28
4         Angola  1901    662.40
..           ...   ...       ...
188    Venezuela  1901   6646.50
189      Vietnam  1901   7542.12
190  Yemen, Rep.  1901   5892.35
191       Zambia  1901   7465.37
88        Kosovo  1991  25839.07

[193 rows x 3 columns]

In [18]:
df_gdp[df_gdp['Year'] == 1901]['GDP_pp'].to_frame()

       GDP_pp
0      613.99
23    1062.01
46    1807.76
69    3352.50
92     525.76
...       ...
4304   766.21
4327   572.96
4350   729.39
4373   532.38
4396   385.69

[192 rows x 1 columns]